default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ...
  host:  127.0.0.1
  port: 3306

development:
  <<: *default
  database: db/development.sqlite3
  database: redmine_db

test:
  <<: *default
  database: db/test.sqlite3
  database: redmine_db

production:
  <<: *default
  database: db/production.sqlite3
  database: redmine_db
